---
- name: Add multiple users on all nodes
  hosts: all
  become: yes

  vars:
    users_to_add:
      - alice
      - bob
      - charlie

  tasks:
    - name: Add users with home directories
      user:
        name: "{{ item }}"
        state: present
        create_home: yes
      loop: "{{ users_to_add }}"
